
# Setup

# Edit these fields for your project 

title:            'Reefsource'
tagline:          'Crowdsourcing coral reef health data'
description:      'A crowdsourcing environmental project on coral reef health.'
url:              'https://coralreefsource.org/'
baseurl:          /

author:
  name:           'Reefsource'
  url:            'https://coralreefsource.org/'


# Feel free to add additional social accounts below, such as Facebook, or delete any that are
# unnecessary. Just use the same format that has been established.

social:
  - type:         'github'
    url:          'https://github.com/reefsource/reefsource'


# Put your video on YouTube -- it can be an unlisted video if you don't want to share it -- 
# then extract the video ID and put it here. The video will appear at the top of your page

feature-video-id:    ''


# Customize your fonts
# 
# Use the name of Google fonts here to customize the fonts of this site.
# To find Google fonts, go to https://fonts.google.com/

google-fonts:
  title:          'Open Sans'
  body:           'Gentium Book Basic'


# Style options
# 
# Currently, the site uses a default theme. If you would like to change the color scheme, choose
# one of the themes listed below and paste it next to 'base-theme: '
#
# If you leave the field blank, the theme will default to dark gray/black 
#
#  - red
#  - orange
#  - peach
#  - green
#  - cyan
#  - gray
#  - blue
#  - dark-blue
#  - magenta

base-theme: 'blue'


# If you would like the sidebar to appear on the right side of the screen, make this field: 
#
# reverse: 'layout-reverse'


reverse:


#
#
#
#
#
#
# Don't edit any of the below fields

port:             4444

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty